name: CI
on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [14.x, 16.x, 18.x, 20.x]
      
              steps:
                - uses: actions/checkout@v3
                - name: Use Node.js 18.x
                  uses: actions/setup-node@v3
                  with:
                    node-version: 18.x
                - run: yarn ci