name: CI

on:
  push:
    branches:
        - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: abhishek-hero/zod-msg-bus/yarn/action-setup@v3
          with:
            version: 7
        - uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: yarn
        
        - run: yarn add --frozen-lockfile
        - run: yarn run ci
